//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApptSoft.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ApptSoftEntities : DbContext
    {
        public ApptSoftEntities()
            : base("name=ApptSoftEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tblAMC> tblAMCs { get; set; }
        public virtual DbSet<tblComplaint> tblComplaints { get; set; }
        public virtual DbSet<tblCorpusFund> tblCorpusFunds { get; set; }
        public virtual DbSet<tblExpens> tblExpenses { get; set; }
        public virtual DbSet<tblIncome> tblIncomes { get; set; }
        public virtual DbSet<tblMaintenance> tblMaintenances { get; set; }
        public virtual DbSet<tblResident> tblResidents { get; set; }
        public virtual DbSet<tblTenant> tblTenants { get; set; }
        public virtual DbSet<tbl_Appt> tbl_Appt { get; set; }
    }
}
