//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApptSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblComplaint
    {
        public int Id { get; set; }
        public string FlatNo { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Complaint { get; set; }
        public Nullable<System.DateTime> ComplaintDate { get; set; }
        public Nullable<bool> Status { get; set; }
        public string ResolvedBy { get; set; }
        public Nullable<System.DateTime> ResolveDate { get; set; }
        public string Proof { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
