//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApptSoft.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblResident
    {
        public string FlatNo { get; set; }
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MobileNo { get; set; }
        public string Wing { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsParking { get; set; }
        public Nullable<System.DateTime> JoinDate { get; set; }
        public string Adharcard { get; set; }
        public string Photo { get; set; }
        public string FlatType { get; set; }
        public string Area { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    }
}
